import { getLocales } from "expo-localization";
import { I18n } from "i18n-js";

const translations = {
    en: {
        common: {
            appName: "AutoCare",
            welcome: "Welcome",
            back: "Back",
            cancel: "Cancel",
        },
        select: {
            placeholder: "Choose option",
            noOptions: "No options available.",
        },
        splash: {
            tagline: "Smart vehicle diagnostics for your car",
            loading: "Preparing system...",
        },
        signin: {
            subtitle: "Sign in to continue vehicle diagnostics",
            emailPlaceholder: "Email",
            passwordPlaceholder: "Password",
            button: "Sign In",
            loading: "Signing in...",
            forgotPassword: "Forgot password?",
            noAccount: "Don't have an account? ",
            signUp: "Sign Up",
            errors: {
                invalidCredentials: "Invalid email or password.",
                networkError: "Network error occurred. Please try again.",
                unknownError: "An unknown error occurred. Please try again.",
                signInFailed: "Sign in failed. Please check your credentials and try again.",
            },
        },
        signup: {
            title: "Create a New Account",
            subtitle: "Register to start smart vehicle diagnostics",
            namePlaceholder: "Full Name",
            emailPlaceholder: "Email Address",
            passwordPlaceholder: "Password",
            button: "Create Account",
            loading: "Processing...",
            footerText: "Already have an account? ",
            footerLink: "Sign In",
            errors: {
                requiredFields: "Name, email, and password are required.",
                passwordTooShort: "Password must be at least 6 characters.",
                signUpFailed: "Sign up failed. Please try again.",
                networkError: "Connection to the server failed. Please try again.",
                unknownError: "An unknown error occurred. Please try again.",
            },
        },
        forgotPassword: {
            title: "Forgot Password",
            subtitle: "Enter your email address and we'll send a reset link.",
            emailPlaceholder: "Email Address",
            button: "Send Reset Link",
            success: "The reset link has been sent to your email address, if it is registered.",
            errors: {
                requiredEmail: "Email cannot be empty.",
                sendFailed: "Failed to send the reset link. Please try again.",
                networkError: "Connection to the server failed. Please try again.",
                unknownError: "An unknown error occurred. Please try again.",
            },
        },
        home: {
            title: "Auto Care",
            welcomeTitle: "Welcome to AutoCare!",
            welcomeDescription: "Start by connecting your OBD-II device to view vehicle metrics and run diagnostics.",
            startDiagnose: "Start Diagnosis",
            skipForNow: "Skip for now",
            emptyHistory: "No data yet. Run your first diagnosis.",
            historyTitle: "Your vehicle diagnosis history:",
        },
        profile: {
            title: "User Profile",
            nameFallback: "User",
            emailFallback: "email@none.com",
            userId: "User ID",
            accountStatus: "Account Status",
            activeVerified: "Active & Verified",
            noData: "User data is not available",
            editProfile: "Edit Profile",
            logout: "Log Out",
            logoutTitle: "Sign Out",
            logoutMessage: "Are you sure you want to sign out of this session?",
            logoutErrorTitle: "Error",
            logoutErrorMessage: "Failed to sign out. Please try again.",
            accountLogout: "Sign Out",
        },
        editProfile: {
            title: "Edit Profile",
            subtitle: "Update your profile information or change your password.",
            emailLabel: "Email Address",
            emailHelper: "Email cannot be changed.",
            nameLabel: "Full Name",
            passwordSection: "Change Password (Optional)",
            newPassword: "New Password",
            confirmPassword: "Confirm Password",
            saving: "Saving...",
            save: "Save Changes",
            success: "Profile updated successfully!",
            errors: {
                nameRequired: "Full name cannot be empty.",
                passwordTooShort: "New password must be at least 6 characters.",
                passwordMismatch: "Password confirmation does not match.",
                saveFailed: "Failed to update profile. Please try again.",
                networkError: "Connection to the server failed. Please try again.",
                unknownError: "An unknown error occurred. Please try again.",
            },
        },
        vehicle: {
            brandPlaceholder: "Choose vehicle brand",
            loadingBrands: "Loading vehicle brands...",
            loadBrandsFailed: "Failed to load vehicle brands",
            addVehicle: "Add Vehicle",
            welcomeTitle: "Welcome to AutoCare",
            welcomeDescription: "To get started, add your vehicle from the Garage menu.",
            welcomeDescriptionAlt: "Or press the button below:",
            noVehicleSelected: "No vehicle selected.",
            currentVehicleFallback: "Unknown vehicle",
        },
        bluetooth: {
            chooseDevice: "Choose Device",
            saved: "Saved",
            scanNew: "Scan New",
            manual: "Manual",
            noSavedDevices: "No saved devices.",
            searching: "Searching for devices...",
            noFound: "No devices found.",
            stopScan: "Stop Scanning",
            scanAgain: "Scan Again",
            macLabel: "Bluetooth MAC Address:",
            macPlaceholder: "Example: 00:1D:A5:02:03:57",
            connect: "Connect",
            disconnect: "Disconnect",
            unknownDevice: "Unknown Device",
            unknownAddress: "No address",
            selectBrandHint: "Choose a vehicle brand for more accurate diagnosis results.",
            obdConsoleTitle: "OBD-II Console",
            waitingActivity: "Waiting for data activity...",
            checkingBluetooth: "Checking Bluetooth...",
            bluetoothOff: "Bluetooth Off",
            enableBluetooth: "Enable Bluetooth",
            connecting: "Connecting...",
            connectionFailed: "Connection Failed",
            connected: "Connected!",
            waitingConnection: "Waiting for Connection",
            connectHint: "Tap the connect button on the badge above.",
            readyToUse: "Device is ready to use.",
            manualDevice: "Manual Device",
            noDtcFoundTitle: "No DTC Codes Found",
            noDtcFoundDescription: "No DTC codes were found on your vehicle. It is likely that no issue was detected.",
            startDiagnosis: "Start Diagnosis",
            processingInit: "Processing Initialization...",
        },
        diagnose: {
            title: "Diagnosis",
            scan: "Scan",
            healthyBadge: "HEALTHY (0 DTC)",
            healthyTitle: "Vehicle Healthy!",
            healthyDescription: "No diagnostic trouble code (DTC) history was found in this session.",
            unknownCodeTitle: "Code Not Yet Registered",
            unknownCodeDescription: "The system detected an issue, but details for the codes below are not yet available in our database:",
            resultTitle: "Diagnosis Result",
            modelUnavailable: "Model not detected",
            foundInfo: "Found {count} fault details.",
            loadingTitle: "Loading Data...",
            loadingDescription: "Retrieving diagnosis history from device memory.",
            errorTitle: "An Error Occurred",
            errorDescription: "Failed to load diagnosis result from local database.",
            invalidId: "Invalid diagnosis ID.",
            back: "Back",
            backHome: "Back to Home",
            finish: "Finish",
            sections: {
                symptom: "Symptoms",
                cause: "Possible Causes",
                solution: "Solutions / Repairs",
                additional: "Additional Information",
            },
            print: {
                reportTitle: "Vehicle Diagnosis Report",
                referenceId: "Reference ID",
                vehicleModel: "Vehicle Model",
                date: "Date",
                additionalInfo: "Additional Information",
                unknownCodes: "There are other detected codes that are not yet listed in our database:",
                printError: "An error occurred while creating the PDF document.",
            },
        },
    },
    id: {
        common: {
            appName: "AutoCare",
            welcome: "Selamat Datang",
            back: "Kembali",
            cancel: "Batal",
        },
        select: {
            placeholder: "Pilih opsi",
            noOptions: "Tidak ada opsi.",
        },
        splash: {
            tagline: "Solusi cerdas untuk diagnosa kendaraan Anda",
            loading: "Menyiapkan sistem...",
        },
        signin: {
            subtitle: "Masuk untuk melanjutkan diagnosa kendaraan",
            emailPlaceholder: "Email",
            passwordPlaceholder: "Kata Sandi",
            button: "Masuk",
            loading: "Sedang masuk...",
            forgotPassword: "Lupa kata sandi?",
            noAccount: "Belum punya akun? ",
            signUp: "Daftar",
            errors: {
                invalidCredentials: "Email atau kata sandi salah.",
                networkError: "Terjadi kesalahan jaringan. Silakan coba lagi.",
                unknownError: "Terjadi kesalahan yang tidak diketahui. Silakan coba lagi.",
                signInFailed: "Gagal masuk. Silakan periksa kredensial Anda dan coba lagi.",
            },
        },
        signup: {
            title: "Buat Akun Baru",
            subtitle: "Daftar untuk mulai mendiagnosa kendaraan secara cerdas",
            namePlaceholder: "Nama Lengkap",
            emailPlaceholder: "Alamat Email",
            passwordPlaceholder: "Kata Sandi",
            button: "Buat Akun",
            loading: "Memproses...",
            footerText: "Sudah punya akun? ",
            footerLink: "Masuk",
            errors: {
                requiredFields: "Nama, email, dan kata sandi wajib diisi.",
                passwordTooShort: "Kata sandi harus minimal 6 karakter.",
                signUpFailed: "Gagal mendaftar. Silakan coba lagi.",
                networkError: "Koneksi ke server gagal. Silakan coba lagi.",
                unknownError: "Terjadi kesalahan yang tidak diketahui. Silakan coba lagi.",
            },
        },
        forgotPassword: {
            title: "Lupa Kata Sandi",
            subtitle: "Masukkan alamat email Anda dan kami akan mengirimkan tautan reset.",
            emailPlaceholder: "Alamat Email",
            button: "Kirim Tautan Reset",
            success: "Tautan reset telah dikirim ke email Anda, jika email tersebut terdaftar.",
            errors: {
                requiredEmail: "Email tidak boleh kosong.",
                sendFailed: "Gagal mengirim tautan reset. Silakan coba lagi.",
                networkError: "Koneksi ke server gagal. Silakan coba lagi.",
                unknownError: "Terjadi kesalahan yang tidak diketahui. Silakan coba lagi.",
            },
        },
        home: {
            title: "Auto Care",
            welcomeTitle: "Selamat datang di AutoCare!",
            welcomeDescription: "Mulai dengan menghubungkan perangkat OBD-II Anda untuk melihat metrik kendaraan dan melakukan diagnosa.",
            startDiagnose: "Mulai Diagnosa",
            skipForNow: "Lewati untuk sekarang",
            emptyHistory: "Belum ada data. Lakukan diagnosa pertama Anda.",
            historyTitle: "Riwayat diagnosa kendaraan Anda:",
        },
        profile: {
            title: "Profil Pengguna",
            nameFallback: "Pengguna",
            emailFallback: "email@tidak.ada",
            userId: "User ID",
            accountStatus: "Status Akun",
            activeVerified: "Aktif & Terverifikasi",
            noData: "Data pengguna tidak tersedia",
            editProfile: "Edit Profil",
            logout: "Keluar Akun",
            logoutTitle: "Konfirmasi Keluar",
            logoutMessage: "Apakah Anda yakin ingin keluar dari sesi ini?",
            logoutErrorTitle: "Error",
            logoutErrorMessage: "Gagal keluar dari akun. Silakan coba lagi.",
            accountLogout: "Keluar",
        },
        editProfile: {
            title: "Edit Profil",
            subtitle: "Perbarui informasi profil atau ubah kata sandi Anda.",
            emailLabel: "Alamat Email",
            emailHelper: "Email tidak dapat diubah.",
            nameLabel: "Nama Lengkap",
            passwordSection: "Ubah Kata Sandi (Opsional)",
            newPassword: "Kata Sandi Baru",
            confirmPassword: "Konfirmasi Kata Sandi",
            saving: "Menyimpan...",
            save: "Simpan Perubahan",
            success: "Profil berhasil diperbarui!",
            errors: {
                nameRequired: "Nama lengkap tidak boleh kosong.",
                passwordTooShort: "Kata sandi baru minimal 6 karakter.",
                passwordMismatch: "Konfirmasi kata sandi tidak cocok.",
                saveFailed: "Gagal memperbarui profil. Silakan coba lagi.",
                networkError: "Koneksi ke server gagal. Silakan coba lagi.",
                unknownError: "Terjadi kesalahan yang tidak diketahui. Silakan coba lagi.",
            },
        },
        vehicle: {
            brandPlaceholder: "Pilih Merek Kendaraan",
            loadingBrands: "Memuat merek kendaraan...",
            loadBrandsFailed: "Gagal memuat merek kendaraan",
            addVehicle: "Tambah Kendaraan",
            welcomeTitle: "Selamat Datang di AutoCare",
            welcomeDescription: "Untuk memulai, silakan tambahkan kendaraan Anda di menu Garasi.",
            welcomeDescriptionAlt: "Atau dengan menekan tombol di bawah ini:",
            noVehicleSelected: "Tidak ada kendaraan yang dipilih.",
            currentVehicleFallback: "Kendaraan Umum",
        },
        bluetooth: {
            chooseDevice: "Pilih Perangkat",
            saved: "Tersimpan",
            scanNew: "Pindai Baru",
            manual: "Manual",
            noSavedDevices: "Tidak ada perangkat tersimpan.",
            searching: "Mencari perangkat...",
            noFound: "Tidak ada perangkat ditemukan.",
            stopScan: "Berhenti Pindai",
            scanAgain: "Pindai Ulang",
            macLabel: "MAC Address Bluetooth:",
            macPlaceholder: "Contoh: 00:1D:A5:02:03:57",
            connect: "Hubungkan",
            disconnect: "Putuskan",
            unknownDevice: "Perangkat Tidak Dikenal",
            unknownAddress: "Tidak ada alamat",
            selectBrandHint: "Pilih merek kendaraan untuk hasil diagnosa yang lebih akurat.",
            obdConsoleTitle: "OBD-II Console",
            waitingActivity: "Menunggu aktivitas data...",
            checkingBluetooth: "Memeriksa Bluetooth...",
            bluetoothOff: "Bluetooth Mati",
            enableBluetooth: "Aktifkan Bluetooth",
            connecting: "Menghubungkan...",
            connectionFailed: "Koneksi Gagal",
            connected: "Terhubung!",
            waitingConnection: "Menunggu Koneksi",
            connectHint: "Ketuk tombol hubungkan pada badge di atas.",
            readyToUse: "Perangkat siap digunakan.",
            manualDevice: "Perangkat Manual",
            noDtcFoundTitle: "Tidak Ditemukan Kode DTC",
            noDtcFoundDescription: "Tidak ditemukan kode DTC pada kendaraan Anda. Kemungkinan besar tidak ada masalah yang terdeteksi.",
            startDiagnosis: "Mulai Diagnosa",
            processingInit: "Memproses Inisialisasi...",
        },
        diagnose: {
            title: "Diagnosa",
            scan: "Pindai",
            healthyBadge: "SEHAT (0 DTC)",
            healthyTitle: "Kendaraan Sehat!",
            healthyDescription: "Tidak ditemukan riwayat kode kerusakan (DTC) pada sesi ini.",
            unknownCodeTitle: "Kode Belum Terdaftar",
            unknownCodeDescription: "Sistem mendeteksi adanya kerusakan, namun detail untuk kode di bawah ini belum tersedia pada database kami:",
            resultTitle: "Hasil Diagnosa",
            modelUnavailable: "Model tidak terdeteksi",
            foundInfo: "Ditemukan {count} informasi kerusakan.",
            loadingTitle: "Memuat Data...",
            loadingDescription: "Mengambil riwayat diagnosa dari memori perangkat.",
            errorTitle: "Terjadi Kesalahan",
            errorDescription: "Gagal memuat hasil diagnosa dari database lokal.",
            invalidId: "ID Diagnosa tidak valid.",
            back: "Kembali",
            backHome: "Kembali ke Beranda",
            finish: "Selesai",
            sections: {
                symptom: "Gejala yang Timbul",
                cause: "Kemungkinan Penyebab",
                solution: "Solusi / Perbaikan",
                additional: "Informasi Tambahan",
            },
            print: {
                reportTitle: "Laporan Diagnosa Kendaraan",
                referenceId: "ID Referensi",
                vehicleModel: "Model Kendaraan",
                date: "Tanggal",
                additionalInfo: "Informasi Tambahan",
                unknownCodes: "Terdapat kode lain yang terdeteksi namun belum terdaftar di database kami:",
                printError: "Terjadi kesalahan saat membuat dokumen PDF.",
            },
        },
    },
} as const;

const i18n = new I18n(translations);
const localeCode = getLocales()[0]?.languageCode?.toLowerCase() ?? "en";

i18n.defaultLocale = "en";
i18n.enableFallback = true;
i18n.locale = localeCode === "id" ? "id" : "en";

export default i18n;
